version: 2.1
orbs:
  codecov: codecov/codecov@3.3.0
  ruby: circleci/ruby@2.3.0

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

  restore_sdkmanager_cache:
    steps:
      - restore_cache:
          key: v1-cmdline-tools-{{ checksum "/opt/android/sdk/cmdline-tools/latest/bin/sdkmanager" }}-{{ arch }}

  save_gradle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

  save_sdkmanager_cache:
    steps:
      - save_cache:
          paths:
            - /opt/android/sdk/cmdline-tools
          key: v1-cmdline-tools-{{ checksum "/opt/android/sdk/cmdline-tools/latest/bin/sdkmanager" }}-{{ arch }}

executors:
  android-machine:
    machine:
      image: android:2022.12.1
  android-docker:
    docker:
      - image: cimg/android:2023.12

jobs:
  android-test:
    executor: android-machine
    resource_class: large
    steps:
      - checkout
      - restore_sdkmanager_cache
      - restore_gradle_cache
      - ruby/install-deps:
          with-cache: true
      - run: export CI=true
      - run:
          name: Fastlane - run all tests with coverage report
          command: bundle exec fastlane test
      - run:
          name: Fastlane - run sonar scanner
          command: bundle exec fastlane check
      - save_gradle_cache
      - save_sdkmanager_cache
      - codecov/upload:
          file: library/build/mergedReportDir/jacocoTestReport/jacocoTestReport.xml
      - store_test_results:
          path: library/build/test-results/testDebugUnitTest
      - store_artifacts:
          path: library/build/reports/androidTests/managedDevice/allDevices
          destination: "test_summary"
      - store_artifacts:
          path: library/build/outputs/managed_device_android_test_additional_output
      - store_artifacts:
          path: library/build/mergedReportDir

  deploy-snapshot:
    executor: android-docker
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Prepare for release
          command: |
            ./gradlew generatePomFileForReleasePublication
      - run:
          name: Import GPG key
          command: |
            echo -e "$GPG_PRIVATE_KEY" | gpg --import --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback
            echo -e "$GPG_PRIVATE_KEY" | gpg --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --keyring secring.gpg --export-secret-keys > ~/.gnupg/secring.gpg
      - run:
          name: Publish Snapshot Release
          command: |
            export DEPLOY_VERSION="1.1.0-SNAPSHOT"
            ./gradlew publish -Psigning.secretKeyRingFile=/home/circleci/.gnupg/secring.gpg -Psigning.password="${GPG_PASSPHRASE}" -Psigning.keyId="${GPG_KEY_ID}" -PbuildRelease=true

  deploy-release:
    executor: android-docker
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Prepare for release
          command: |
            ./gradlew generatePomFileForReleasePublication
      - run:
          name: Import GPG key
          command: |
            echo -e "$GPG_PRIVATE_KEY" | gpg --import --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback
            echo -e "$GPG_PRIVATE_KEY" | gpg --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --keyring secring.gpg --export-secret-keys > ~/.gnupg/secring.gpg
      - run:
          name: Publish Snapshot Release
          command: |
            export DEPLOY_VERSION="1.0.1" 
            ./gradlew publish -Psigning.secretKeyRingFile=/home/circleci/.gnupg/secring.gpg -Psigning.password="${GPG_PASSPHRASE}" -Psigning.keyId="${GPG_KEY_ID}" -PbuildRelease=true


  distribute-dev:
    executor: android-docker
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Prepare Fastlane
          command: |
            sudo bundle update
            ./gradlew assembleDebug
      - run:
          name: Distribute to Firebase AppTester
          command: bundle exec fastlane distDev
      - store_artifacts:
          path: /home/circleci/project/app/build/outputs/apk/debug/app-debug.apk
          destination: fastlane-output-debug

  distribute-test:
    executor: android-docker
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Prepare Fastlane
          command: |
            sudo bundle update
            ./gradlew assembleDebug
      - run:
          name: Distribute to Firebase AppTester
          command: bundle exec fastlane distTest
      - store_artifacts:
          path: /home/circleci/project/app/build/outputs/apk/debugTestStage/app-debug.apk
          destination: fastlane-output-debug

workflows:
  workflow:
    jobs:
      - android-test
      - deploy-snapshot:
          name: deploy-snapshot
          context:
            - gpg
            - maven-central
          requires:
            - android-test
          filters:
            branches:
              ignore:
                - main
      - deploy-release:
          name: deploy-release
          context:
            - gpg
            - maven-central
          requires:
            - android-test
          filters:
            branches:
              only: main
      - distribute-dev:
          name: distribute-dev
          requires:
            - android-test
          filters:
            branches:
              ignore:
                - main
                - develop
      - distribute-test:
          name: distribute-test
          requires:
            - android-test
          filters:
            branches:
              only: develop
