# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean createEmptyConfigFile pixel2api30DebugAndroidTest testDebugUnitTest jacocoTestReport --stacktrace")
  end

  desc "Runs sonar scanner"
  lane :check do
    gradle(task: ":library:lintDebug sonar --stacktrace")
  end

  desc "Deploy to Firebase AppTester channel"
  lane :distDev do
    gradle(task: "clean generateAppDistKey generateTrustbadgeConfigFile assembleDebug")
    firebase_app_distribution(
        service_credentials_file: ENV['APP_DIST_SERVICE_ACCOUNT_PATH'],
        app: "1:849831422549:android:238ca47c17a75a8b5a02dc",
        groups: "admins",
        release_notes: "",
    )
  end

end
